
#### THEME ####
general.import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

##### GENERAL #####
[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
# decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 1
startup_mode = "Maximized"
# decorations = "None"

[window.dimensions]
columns = 100
lines = 30

#[window.padding]
#x = 14
#y = 14

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 14

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true
